version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          when: always
          name: Cleaning reports
          command: npm run clean-reports
      - run:
          when: always
          name: Running cypress tests
          command: npx cypress run
      - run:
          when: always
          name: Generate MochaAwesome Reports
          command: npm run create-report 
      - store_test_results:
          path: mochawesome-unmerged-reports
      - store_artifacts:
          path: mochawesome-report
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: mochawesome-report/assets
      - run:
          when: always
          name: Slack Custom Reporting via cli command
          command: npm run slack-reporter
